@startuml
!pragma layout smetana
Class Main
CLass Building
Class Rooms

Main : Static void main

Building : - ArrayList<Rooms>
Building : - getRooms
Building : - getNumberOfFloors
Building : - final ArrayList<Rooms>
Building : + int numberOfBathrooms()
Building : + int getNumberOfFloors()
Building : + boolean isOfficeBuilding()

Rooms : - int numberOfDoors
Rooms : - int numberOfLamps
Rooms : - int numberOfWindows
Rooms : + Rooms(int numberOfDoors, int numberOfLamps, int numberOfWindows)
Rooms : + int getNumberOfDoors()
Rooms : + int  getNumberOfLamps()

Building <|-- Rooms
Main *-- Building
@enduml
